services:
  dev:
    extends:
      file: compose.common.yaml
      service: common
    build:
      context: .
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}:z

volumes:
  claude-projects:
    name: claude-projects
  devenv-cache:
    name: devenv-cache
  devenv-mason:
    name: devenv-mason
