name: agent-${TASK:?TASK is not set}

services:
  agent:
    extends:
      file: compose.common.yaml
      service: common
    working_dir: ${PWD}.agent/${TASK}
    volumes:
      - ${PWD}.agent/${TASK}:${PWD}.agent/${TASK}:z
      - ${PWD}/.git:${PWD}/.git:z
      - ${PWD}/.git/config:${PWD}/.git/config:ro,z
      - ${PWD}/.git/hooks:${PWD}/.git/hooks:ro,z

volumes:
  claude-projects:
    name: claude-projects
